#!/bin/bash

# Fix icon imports - Material Design (Md*) to Feather Icons (Fi*)
echo "🎨 Fixing icon imports..."

FILES=$(find app -name "*.tsx" -o -name "*.ts")

for file in $FILES; do
  if ! grep -q "react-icons/fi" "$file"; then
    continue
  fi
  
  echo "Processing: $file"
  
  # Common icon mappings (Material Design -> Feather Icons)
  sed -i '' 's/MdHome/FiHome/g' "$file"
  sed -i '' 's/MdShoppingCart/FiShoppingCart/g' "$file"
  sed -i '' 's/MdPeople/FiUsers/g' "$file"
  sed -i '' 's/MdBarChart/FiBarChart/g' "$file"
  sed -i '' 's/MdInventory/FiPackage/g' "$file"
  sed -i '' 's/MdLocalShipping/FiTruck/g' "$file"
  sed -i '' 's/MdSettings/FiSettings/g' "$file"
  sed -i '' 's/MdTrendingUp/FiTrendingUp/g' "$file"
  sed -i '' 's/MdAttachMoney/FiDollarSign/g' "$file"
  sed -i '' 's/MdWarning/FiAlertTriangle/g' "$file"
  sed -i '' 's/MdRefresh/FiRefreshCw/g' "$file"
  sed -i '' 's/MdToggleOn/FiToggleRight/g' "$file"
  sed -i '' 's/MdToggleOff/FiToggleLeft/g' "$file"
  sed -i '' 's/MdAdd/FiPlus/g' "$file"
  sed -i '' 's/MdSend/FiSend/g' "$file"
  sed -i '' 's/MdEmail/FiMail/g' "$file"
  sed -i '' 's/MdCheckCircle/FiCheckCircle/g' "$file"
  sed -i '' 's/MdSchedule/FiClock/g' "$file"
  sed -i '' 's/MdDrafts/FiFileText/g' "$file"
  sed -i '' 's/MdArrowBack/FiArrowLeft/g' "$file"
  sed -i '' 's/MdDownload/FiDownload/g' "$file"
  sed -i '' 's/MdDelete/FiTrash2/g' "$file"
  sed -i '' 's/MdEdit/FiEdit2/g' "$file"
  sed -i '' 's/MdSearch/FiSearch/g' "$file"
  sed -i '' 's/MdFilterList/FiFilter/g' "$file"
  sed -i '' 's/MdGridView/FiGrid/g' "$file"
  sed -i '' 's/MdViewList/FiList/g' "$file"
  sed -i '' 's/MdArrowForward/FiArrowRight/g' "$file"
  sed -i '' 's/MdRemoveCircle/FiMinusCircle/g' "$file"
  sed -i '' 's/MdPersonAdd/FiUserPlus/g' "$file"
  sed -i '' 's/MdLogin/FiLogIn/g' "$file"
  sed -i '' 's/MdClose/FiX/g' "$file"
  sed -i '' 's/MdInfo/FiInfo/g' "$file"
  sed -i '' 's/MdError/FiAlertCircle/g' "$file"
  sed -i '' 's/MdCheck/FiCheck/g' "$file"
  sed -i '' 's/MdCancel/FiXCircle/g' "$file"
  sed -i '' 's/MdMoreVert/FiMoreVertical/g' "$file"
  sed -i '' 's/MdMoreHoriz/FiMoreHorizontal/g' "$file"
  sed -i '' 's/MdVisibility/FiEye/g' "$file"
  sed -i '' 's/MdVisibilityOff/FiEyeOff/g' "$file"
  sed -i '' 's/MdNotifications/FiBell/g' "$file"
  sed -i '' 's/MdCalendarToday/FiCalendar/g' "$file"
  sed -i '' 's/MdDescription/FiFileText/g' "$file"
  sed -i '' 's/MdAttachment/FiPaperclip/g' "$file"
  sed -i '' 's/MdLink/FiLink/g' "$file"
  sed -i '' 's/MdContentCopy/FiCopy/g' "$file"
  sed -i '' 's/MdSave/FiSave/g' "$file"
  sed -i '' 's/MdPrint/FiPrinter/g' "$file"
  sed -i '' 's/MdShare/FiShare2/g' "$file"
  sed -i '' 's/MdStar/FiStar/g' "$file"
  sed -i '' 's/MdFavorite/FiHeart/g' "$file"
  sed -i '' 's/MdThumbUp/FiThumbsUp/g' "$file"
  sed -i '' 's/MdComment/FiMessageSquare/g' "$file"
  sed -i '' 's/MdChat/FiMessageCircle/g' "$file"
  sed -i '' 's/MdPhone/FiPhone/g' "$file"
  sed -i '' 's/MdLocationOn/FiMapPin/g' "$file"
  sed -i '' 's/MdImage/FiImage/g' "$file"
  sed -i '' 's/MdFolder/FiFolder/g' "$file"
  sed -i '' 's/MdUpload/FiUpload/g' "$file"
  sed -i '' 's/MdCloudUpload/FiUploadCloud/g' "$file"
  sed -i '' 's/MdCloudDownload/FiDownloadCloud/g' "$file"
  sed -i '' 's/MdLock/FiLock/g' "$file"
  sed -i '' 's/MdLockOpen/FiUnlock/g' "$file"
  sed -i '' 's/MdPerson/FiUser/g' "$file"
  sed -i '' 's/MdGroup/FiUsers/g' "$file"
  sed -i '' 's/MdBusiness/FiBuilding/g' "$file"
  sed -i '' 's/MdStore/FiShoppingBag/g' "$file"
  sed -i '' 's/MdReceipt/FiFileText/g' "$file"
  sed -i '' 's/MdPayment/FiCreditCard/g' "$file"
  sed -i '' 's/MdShoppingBag/FiShoppingBag/g' "$file"
  sed -i '' 's/MdLocalOffer/FiTag/g' "$file"
  sed -i '' 's/MdLabel/FiTag/g' "$file"
  sed -i '' 's/MdBookmark/FiBookmark/g' "$file"
  sed -i '' 's/MdFlag/FiFlag/g' "$file"
  sed -i '' 's/MdHelp/FiHelpCircle/g' "$file"
  sed -i '' 's/MdInfoOutline/FiInfo/g' "$file"
  sed -i '' 's/MdErrorOutline/FiAlertCircle/g' "$file"
  sed -i '' 's/MdWarningAmber/FiAlertTriangle/g' "$file"
  sed -i '' 's/MdCheckCircleOutline/FiCheckCircle/g' "$file"
  sed -i '' 's/MdRadioButtonUnchecked/FiCircle/g' "$file"
  sed -i '' 's/MdRadioButtonChecked/FiCheckCircle/g' "$file"
  sed -i '' 's/MdArrowUpward/FiArrowUp/g' "$file"
  sed -i '' 's/MdArrowDownward/FiArrowDown/g' "$file"
  sed -i '' 's/MdKeyboardArrowLeft/FiChevronLeft/g' "$file"
  sed -i '' 's/MdKeyboardArrowRight/FiChevronRight/g' "$file"
  sed -i '' 's/MdKeyboardArrowUp/FiChevronUp/g' "$file"
  sed -i '' 's/MdKeyboardArrowDown/FiChevronDown/g' "$file"
  sed -i '' 's/MdExpandMore/FiChevronDown/g' "$file"
  sed -i '' 's/MdExpandLess/FiChevronUp/g' "$file"
  sed -i '' 's/MdMenu/FiMenu/g' "$file"
  sed -i '' 's/MdApps/FiGrid/g' "$file"
  sed -i '' 's/MdDashboard/FiLayout/g' "$file"
  sed -i '' 's/MdViewModule/FiGrid/g' "$file"
  sed -i '' 's/MdViewQuilt/FiGrid/g' "$file"
  sed -i '' 's/MdViewStream/FiList/g' "$file"
  sed -i '' 's/MdViewDay/FiColumns/g' "$file"
  sed -i '' 's/MdViewWeek/FiColumns/g' "$file"
  sed -i '' 's/MdCalendar/FiCalendar/g' "$file"
  sed -i '' 's/MdEvent/FiCalendar/g' "$file"
  sed -i '' 's/MdAccessTime/FiClock/g' "$file"
  sed -i '' 's/MdTimer/FiClock/g' "$file"
  sed -i '' 's/MdHistory/FiClock/g' "$file"
  sed -i '' 's/MdUpdate/FiRefreshCw/g' "$file"
  sed -i '' 's/MdSync/FiRefreshCw/g' "$file"
  sed -i '' 's/MdCached/FiRefreshCw/g' "$file"
  sed -i '' 's/MdAutorenew/FiRefreshCw/g' "$file"
done

echo "✅ Icon fixes complete!"

