-- Migration: Create embedding cache table for AI operations
-- Description: Cache generated embeddings to reduce API calls and costs
-- PERFORMANCE: Reduces expensive AI API calls by caching embeddings

-- Create embedding cache table
CREATE TABLE IF NOT EXISTS embedding_cache (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cache_key TEXT NOT NULL UNIQUE,  -- Hash of the text that was embedded
  text_content TEXT NOT NULL,       -- Original text (for debugging/verification)
  embedding vector(768),            -- Gemini text-embedding-004 embedding (768 dimensions)
  model_name TEXT NOT NULL DEFAULT 'text-embedding-004',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_used_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  use_count INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT chk_embedding_length CHECK (vector_dims(embedding) = 768)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_embedding_cache_key
  ON embedding_cache(cache_key);

CREATE INDEX IF NOT EXISTS idx_embedding_cache_last_used
  ON embedding_cache(last_used_at DESC);

CREATE INDEX IF NOT EXISTS idx_embedding_cache_model
  ON embedding_cache(model_name);

-- Index for vector similarity search (if needed)
CREATE INDEX IF NOT EXISTS idx_embedding_cache_vector
  ON embedding_cache USING ivfflat(embedding vector_cosine_ops)
  WITH (lists = 100);

-- Enable RLS
ALTER TABLE embedding_cache ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Authenticated users can read all cached embeddings
CREATE POLICY "Authenticated users can read embedding cache"
  ON embedding_cache FOR SELECT
  TO authenticated
  USING (true);

-- RLS Policy: System can insert new embeddings
CREATE POLICY "Authenticated users can insert embedding cache"
  ON embedding_cache FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- RLS Policy: System can update usage stats
CREATE POLICY "Authenticated users can update embedding cache"
  ON embedding_cache FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Function to clean up old cached embeddings (keep frequently used ones)
CREATE OR REPLACE FUNCTION cleanup_embedding_cache(
  days_old INTEGER DEFAULT 90,
  min_use_count INTEGER DEFAULT 2
)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  deleted_count INTEGER;
BEGIN
  -- Delete embeddings that:
  -- 1. Haven't been used in X days AND
  -- 2. Have been used fewer than Y times
  DELETE FROM embedding_cache
  WHERE last_used_at < NOW() - (days_old || ' days')::INTERVAL
    AND use_count < min_use_count;

  GET DIAGNOSTICS deleted_count = ROW_COUNT;

  RETURN deleted_count;
END;
$$;

-- Function to get or create cached embedding
-- This would be called from the application layer
COMMENT ON TABLE embedding_cache IS
  'Caches AI-generated embeddings to reduce API calls and costs. '
  'Each cached entry includes usage statistics for LRU cleanup.';

COMMENT ON COLUMN embedding_cache.cache_key IS
  'SHA256 hash of the normalized text content for fast lookups';

COMMENT ON COLUMN embedding_cache.text_content IS
  'Original text that was embedded (stored for verification and debugging)';

COMMENT ON COLUMN embedding_cache.embedding IS
  'Vector embedding generated by Gemini text-embedding-004 model (768 dimensions)';

COMMENT ON COLUMN embedding_cache.use_count IS
  'Number of times this embedding has been retrieved from cache (for LRU cleanup)';

COMMENT ON FUNCTION cleanup_embedding_cache IS
  'Removes old, infrequently-used embeddings to keep cache size manageable';

-- Log success
DO $$
BEGIN
  RAISE NOTICE '==================================================';
  RAISE NOTICE 'Embedding Cache Table Created Successfully!';
  RAISE NOTICE '==================================================';
  RAISE NOTICE 'This will significantly reduce AI API costs for:';
  RAISE NOTICE '- SKU mapping operations';
  RAISE NOTICE '- Semantic search queries';
  RAISE NOTICE '- Product similarity comparisons';
  RAISE NOTICE '==================================================';
END $$;
